### PR TITLE
chore: ingress as multi source app

### PR DESCRIPTION
**Pull request by carslen**
- Deployment of `ingress-nginx` migrated to be deployed as multi-source app.
- Environment specific values cleaned up and removed unnecessary settings.
- renamed ingress-nginx ArgoCD app from `hotel-budapest-ingress-nginx` to `int-ingress-nginx`.
- `devsecops-testing` will be updated to latest ingress controller helm chart (4.8.3) for testing.

### CODE REVIEW

**Review by FaGru3n — COMMENTED** [review]
i guess this looks fine, but did you tested devsecops cluster on new version, currently i see version 4.7.1 on the argo or do you want to combine it?

**Comment by FaGru3n** [comment]
did you then not also have to update 
https://github.com/catenax-ng/k8s-cluster-stack/blob/main/environments/core/applicationsets/ingress-applicationset.yaml for dev and beta cluster?

**Comment by carslen** [comment]
> did you then not also have to update https://github.com/catenax-ng/k8s-cluster-stack/blob/main/environments/core/applicationsets/ingress-applicationset.yaml for dev and beta cluster?

OK, it's not that obvious, but the appset definition you linked, isn't active anymore:
https://github.com/catenax-ng/k8s-cluster-stack/blob/9b1d76ad7f979c2bf0af95ffb00286f14ff47b0a/environments/core/kustomization.yaml#L9

All envs already use the multi-source applicationset, but use a branch as `targetRevision`:

https://github.com/catenax-ng/k8s-cluster-stack/blob/9b1d76ad7f979c2bf0af95ffb00286f14ff47b0a/environments/core/kustomization.yaml#L10

https://github.com/catenax-ng/k8s-cluster-stack/blob/9b1d76ad7f979c2bf0af95ffb00286f14ff47b0a/environments/core/applicationsets/ingress-multisource-applicationset.yaml#L17

This PR is to switch to main branch.

**Review by FaGru3n — APPROVED** [review]
LGTM

**Comment by carslen** [comment]
Merged. 

After syncing `core-config` (to update the applicationSet) and syncing `devsecops-testing-ingress-nginx` Helm Chart version 4.8.3 successfully deployed to devsecopst-testing cluster.

**Pull request merged**
