### PR TITLE
move argocd ingress into respective argocd environment

### PR DESCRIPTION
**Pull request by ricogu**

### CODE REVIEW

**Review by carslen — CHANGES_REQUESTED** [review]
Some remarks:
- the `values-*.yaml` files for core and HB are obsolate, aren't they?
- the secret _azuredns-config_ is still unmanaged and should be added to repo (using the [AVP/Vault](https://vault.vault.demo.catena-x.net/ui/vault/secrets/devsecops/show/azure/demo.catena-x.net/azuredns-config))
- content of `values.yaml` is not directly sensitive, but should be fetched from [Vault](https://vault.vault.demo.catena-x.net/ui/vault/secrets/devsecops/show/azure/demo.catena-x.net/tenant) too
- unhappy with having `ingress-vault-wirdcard-tls.yaml` still as part of _tls_ Chart, but let's think about this later

I'd like to test the Helm AVP plugin integration with this _tls_ Chart against the new, currently unused _DEV_ cluster @SebastianBezold had mentioned yesterday. What do you think?

**Review by SebastianBezold — APPROVED** [review]
LGTM

**Comment by SebastianBezold** [comment]
> Some remarks:
> 
> * the `values-*.yaml` files for core and HB are obsolate, aren't they?
> * the secret _azuredns-config_ is still unmanaged and should be added to repo (using the [AVP/Vault](https://vault.vault.demo.catena-x.net/ui/vault/secrets/devsecops/show/azure/demo.catena-x.net/azuredns-config))
> * content of `values.yaml` is not directly sensitive, but should be fetched from [Vault](https://vault.vault.demo.catena-x.net/ui/vault/secrets/devsecops/show/azure/demo.catena-x.net/tenant) too
> * unhappy with having `ingress-vault-wirdcard-tls.yaml` still as part of _tls_ Chart, but let's think about this later
> 
> I'd like to test the Helm AVP plugin integration with this _tls_ Chart against the new, currently unused _DEV_ cluster @SebastianBezold had mentioned yesterday. What do you think?

The values should indeed be obsolete now. The azuredns-config changes are part of another task. So in my opinion, we can handle that with a separate PR

**Comment by ricogu** [comment]
> Some remarks:
> 
> * the `values-*.yaml` files for core and HB are obsolate, aren't they?

have to optimize this after https://jira.catena-x.net/browse/A1ODT-501

> * the secret _azuredns-config_ is still unmanaged and should be added to repo (using the [AVP/Vault](https://vault.vault.demo.catena-x.net/ui/vault/secrets/devsecops/show/azure/demo.catena-x.net/azuredns-config))

task: https://jira.catena-x.net/browse/A1ODT-497

> * content of `values.yaml` is not directly sensitive, but should be fetched from [Vault](https://vault.vault.demo.catena-x.net/ui/vault/secrets/devsecops/show/azure/demo.catena-x.net/tenant) too

which `values.yaml` are you referring to?

> * unhappy with having `ingress-vault-wirdcard-tls.yaml` still as part of _tls_ Chart, but let's think about this later
> 

task: https://jira.catena-x.net/browse/A1ODT-501

> I'd like to test the Helm AVP plugin integration with this _tls_ Chart against the new, currently unused _DEV_ cluster @SebastianBezold had mentioned yesterday. What do you think?

**Comment by carslen** [comment]
> @carslen

> > * content of `values.yaml` is not directly sensitive, but should be fetched from [Vault](https://vault.vault.demo.catena-x.net/ui/vault/secrets/devsecops/show/azure/demo.catena-x.net/tenant) too
> 
> which `values.yaml` are you referring to?

The one I've mentioned :) -> https://github.com/catenax-ng/k8s-cluster-stack/blob/feature/A1ODT-493-tls-cleanup/apps/tls/values.yaml

As my remarks are covered with other subtasks, then approval is fine for mee too.

**Comment by ricogu** [comment]
> Some remarks:
> 
> * the `values-*.yaml` files for core and HB are obsolate, aren't they?

we still need `values-*.yaml` in tls app so that it can request/maintain certificates on different cluster with different dns domain

**Pull request merged**
